<center><h1> Numpy Assignemnt </h1></center>

### Write the Code in empty cells to produce it's exact below output

## Import Numpy

In [2]:
import numpy as np

## Creating 3 Arrays (1-D, 2-D, 3-D)

In [12]:
oned_arr=np.array([1,5,7,4])
oned_arr

array([1, 5, 7, 4])

In [14]:
twod_arr =np.array([[1,2,5],
        [4,5,9]])
twod_arr

array([[1, 2, 5],
       [4, 5, 9]])

In [15]:
threed_arr=np.array([[[ 1,  3,  5],
        [ 4,  9, 10],
        [ 5,  3,  2]],

       [[ 4,  6, 10],
        [ 5,  9,  8],
        [10,  3,  4]]])
threed_arr

array([[[ 1,  3,  5],
        [ 4,  9, 10],
        [ 5,  3,  2]],

       [[ 4,  6, 10],
        [ 5,  9,  8],
        [10,  3,  4]]])

## Use attributes of Numpy (ndim, shape, size, dtype, itemsize) for all above 3 arrays

In [19]:
oned_arr.ndim
twod_arr.ndim
threed_arr.ndim

3

In [22]:
oned_arr.shape
twod_arr.shape
threed_arr.shape

(2, 3, 3)

In [ ]:
threed_arr.dtype
twod_arr.size
oned_arr.itemsize

8

## Create Range Arrays

In [116]:
# This matrix (5x5) will have elements within the range of 0-99 with step size of 4


In [41]:


arr = np.arange(0, 100, 4).reshape(5, 5)
arr


array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

## Creating a Random array within range of 0-50

In [120]:
# This Matrix (4x6) will have random integers within range 0-50


In [51]:
arr =np.random.randint(0,50 , size=(4,6))
arr


array([[47, 12,  2, 43, 30, 41],
       [13, 22, 17, 38, 21, 44],
       [ 3, 31, 15, 26, 29,  3],
       [ 3, 37,  8, 41, 17, 17]], dtype=int32)

## Creating a Random array within range of 0.0 and 1.0 (Float)

In [122]:
# This 2x3 Matrix will have the float range from 0.0 to 1.0


In [59]:
arr = np.random.uniform(0.0,1.0 , (2, 3))
arr

array([[0.69288495, 0.47039938, 0.64696059],
       [0.18465411, 0.53134537, 0.22867536]])

In [56]:
arr.dtype

dtype('float64')

## Array Indexing

In [60]:
# Create the follwing array
arr = np.array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])
arr

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [62]:
## Return Unique Elements in the array
arr1 = np.unique(arr)
arr1

array([ 3,  5,  8, 12, 13, 15, 22, 25, 26, 30, 31, 34, 37, 38, 40, 41, 42,
       46, 48, 49])

In [63]:
# Return the First Row (Indexing starts with 0)
first_row=arr[0]
first_row

array([15, 42, 41, 38, 49,  3])

In [67]:
# Return 3rd Row 3rd Element (Indexing starts with 0)
three_row =arr[2,2]
print(three_row)

12


In [68]:
# Returns 1st Row 4th Element (Indexing starts with 0)
first_row=arr[0,3]
print(first_row)

38


In [69]:
# Create the follwoing array
arr = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [70]:
# Return 1st array
first_array=arr[0]
first_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
# Returns 1st array 2nd row 3rd element
first_array=arr[0,1,2]
print(first_array)

5


## Array Slicing

<h4> <b> Slicing 1-Dimensional Arrays </b> </h4>

In [ ]:
# Create the 1-Dimensional array 
arr= np.array([1, 5, 7, 4])
arr

array([1, 5, 7, 4])

In [77]:
# Produce the follwing Result
result = arr[2:4]
result

array([7, 4])

<h4> <b> Slicing 2-Dimensional Arrays </b> </h4>

In [78]:
# Carrreate the 2-Dimensional array 
arr1 = np.array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])
arr1

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [79]:
# Produce the follwoing result
result = arr1[:, 1:3]
result


array([[42, 41],
       [ 8, 25],
       [22, 12],
       [30, 46]])

In [143]:
# Produce the follwoing result
result = arr1[:,0:3]
result

array([[15, 42, 41],
       [13,  8, 25],
       [34, 22, 12],
       [31, 30, 46]])

In [81]:
# Produce the following result
result = arr1[1:3, 3:5]
result


array([[25, 48],
       [37, 26]])

## Assigning Values to Arrays (Broadcasting)

<h4> <b> 1-Dimensional Arrays Broadcasting </b> </h4>

In [82]:
# Create 1-D Array
arr= np.array([1, 5, 7, 4])
arr

array([1, 5, 7, 4])

In [84]:
# Change Index 3 value to 99
arr[3]=99
arr

array([ 1,  5,  7, 99])

In [87]:
# Change the Index vales by slicing
arr[1:4]=[888]
arr


array([  1, 888, 888, 888])

<h4> <b> 2-Dimensional Arrays Broadcasting </b> </h4>

In [91]:
# Create the 2-D Array

arr = np.array([[1, 2, 5],
                [4, 6, 9]])
arr


array([[1, 2, 5],
       [4, 6, 9]])

In [92]:
# Change 1st row 2nd value 2 to 100
arr[0,1]=100
arr

array([[  1, 100,   5],
       [  4,   6,   9]])

In [95]:
# Change values by slicing the matrix and produce the follwoing results
arr[0,1]=777
arr

array([[  1, 777,   5],
       [  4,   6,   9]])

## Numpy Operations

<h4> <b> Arithmetic Operations </b> </h4>

In [96]:
# Create the follwoing array
arr = np.array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])
arr

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [97]:
# Add +10 to each element
result =arr+10
result

array([[25, 52, 51, 48, 59, 13],
       [23, 18, 35, 35, 58, 15],
       [44, 32, 22, 47, 36, 58],
       [41, 40, 56, 50, 15, 50]])

In [98]:
# Subtract -10 from each element
result = arr-10
result

array([[ 5, 32, 31, 28, 39, -7],
       [ 3, -2, 15, 15, 38, -5],
       [24, 12,  2, 27, 16, 38],
       [21, 20, 36, 30, -5, 30]])

In [99]:
# Multiplying each element with 9
reslut = arr*9
result

array([[ 5, 32, 31, 28, 39, -7],
       [ 3, -2, 15, 15, 38, -5],
       [24, 12,  2, 27, 16, 38],
       [21, 20, 36, 30, -5, 30]])

In [101]:
# Dividing each element with 2
result = arr /2
result

array([[ 7.5, 21. , 20.5, 19. , 24.5,  1.5],
       [ 6.5,  4. , 12.5, 12.5, 24. ,  2.5],
       [17. , 11. ,  6. , 18.5, 13. , 24. ],
       [15.5, 15. , 23. , 20. ,  2.5, 20. ]])

<h4> <b> Statistical Operations </b> </h4>

In [102]:
# Creating a New Array
arr = np.array([[ 2,  3,  4],
       [ 4,  3, 17],
       [89, 33, 12]])
arr

array([[ 2,  3,  4],
       [ 4,  3, 17],
       [89, 33, 12]])

In [106]:
# Sum Operations
# Produce total sum, row wise sum (first elements), columns wise sum
total_sum = np.sum(arr)
print(total_sum)



167


In [109]:
column_sum = np.sum(arr, axis=0)
column_sum


array([95, 39, 33])

In [108]:
row_sum = np.sum(arr, axis=1)
row_sum


array([  9,  24, 134])

In [116]:
# Calculate Mean, Meadian, Square root, minimum, maximum values of new_arr
new_arr = np.array([[ 2,  3,  4],
                    [ 4,  3, 17],
                    [89, 33, 12]])
mean =np. mean(new_arr)
mean


np.float64(18.555555555555557)

In [118]:
meadian = np.median(new_arr)
meadian

np.float64(4.0)

In [119]:
np.sqrt(new_arr)


array([[1.41421356, 1.73205081, 2.        ],
       [2.        , 1.73205081, 4.12310563],
       [9.43398113, 5.74456265, 3.46410162]])

In [120]:
np.min(new_arr)


np.int64(2)

In [121]:
np.max(new_arr)


np.int64(89)